templates/macros/macros.html

I really like this theme, thanks for creating it!
I noticed the summaries of pages get escaped in the posts template. A simple `| safe` addition fixes it.

fix page summary html escaping

---

templates/macros/macros.html

This fixes #3.
Zola already skips draft pages by default, and includes then when the `--drafts` flag is set.
This PR also fixes that the DRAFTS label only appeared when a date is set. It was also missing from the posts list so I added it inside the pages_list macro.
I also added a missing {% if page.date %} check.

remove always skipping drafts

---

content/_index.md
content/posts/_index.md
templates/index.html
templates/section.html

I discovered that the posts template is currently hardcoding the section path and can't really be reused for other sections.
This is done to display the posts on the root page.
This PR refactors the posts template into a more generic `section.html` template which [gets used for all sections by zola](https://www.getzola.org/documentation/templates/pages-sections/#section-variables).
To fix the issue with displaying posts on the root page, I added a custom `section_path` frontmatter variable to overwrite the section used in the template.See the root `_index.html` to how it is used.

refactor posts to section template, add extra section frontmatter variable to overwrite section path

---

content/_index.md
content/posts/_index.md

The index page shows Projects and About insted of paginating and showing blogs. This will fix this issue. If this isn't the desired behavious, please close the PR
Before:
After:

fix: index page shows Projects and About instead of blogs

---

templates/partials/nav.html

The "rel" html attribute defines the relationship between the linked resource and the current document. The "me" value indicates, that the current document (zola website) represents the person who owns the linked content. This is necessary for mastodon website verification.
See:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel
https://docs.joinmastodon.org/user/profile/#verification
I think it's safe to add the `rel` attribute to all social links, not just mastodon. If there are concerns, a conditional could be introduced.

feat: Add relationship attribute to social links

---

README.md
config.toml
content/posts/math-symbols-test.md
templates/partials/header.html

I wanted to add this because it really bothered me that we have to use `\(..\)` to do inline math by default in mathjax. GitHub markdown supports $..$ inline math properly, and when we open markdown, they'll have it rendered correctly. This doesn't happen with `(\..\)` .  So any post page that uses inline math, when viewed in github won't have correct rendering by default if we use `(\..\)` but it will if we use `$..$`. The $..$ way is also more friendly with pandoc if needed, so I thought adding support for it would be nice.

Add $ inline math support with mathjax

---

README.md
templates/partials/header.html

* add meta tag support for individual pages
```yaml
...
extra:
meta: 
- property: og:title 
content: the title of the page 
- property: og:description
content: the description of the page 
```
The YAML code above will generate `<meta property="og:title" content="the title of the page"/>` and `<meta property="og:description" content="the description of the page"/>`.
* default the `og:title` and `og:description` to the pages' title and description.

Add meta tag support

---

sass/parts/_header.scss
templates/partials/nav.html

Hello!
I noticed a bit of jumpiness toggling between light/dark mode, and saw that some of the HTML could be cleaned up too.
Follows up on #26 
- `href=""` -> `href="#"`, no reload
- Moved inline CSS to `header.sass` for #hygeine :)
| Before | After |
|-|-|
|<video src="https://github.com/not-matthias/apollo/assets/2782749/c80c7dc0-72bd-4a99-8f2d-b64c810dcf4b" height="77px"></video>|<video src="https://github.com/not-matthias/apollo/assets/2782749/c6e6fa19-3396-4d92-899c-351f122d3afb" height="77px"></video>|

Fix navigation jumpiness on theme toggle click

---

templates/partials/nav.html

Anything other than "toggle" value for theme variable in `config.toml` breaks the website.
In `nav.html`, the closing `</nav>` tag is inside the `endif` block. Hence, if the theme is not set to "toggle", the `nav` tag is never closed, and website breaks.

fix: nav.html: closing nav tag inside endif block.

---

templates/macros/macros.html
templates/section.html
templates/taxonomy_list.html
templates/taxonomy_single.html

- adds `taxonomy_list.html` and `taxonomy_single.html` for zola to fall back on when rendering taxonomies
- made it so `taxonomy_single.html` inherits from `section.html`
- I had to wrap the post list and the title in blocks to override them since they refer to the `section` object explicitly
- added a `list_terms` macro to the macros file to be used in `taxonomy_list.html`

add taxonomy templates

---

sass/fonts.scss
templates/partials/nav.html

This fixes a few incorrect URLs in generated content when deploying sites in a sub-directory, e.g. https://jiggak.github.io/waymenu/

fix 404 errors when deployed to non-root path

---

templates/partials/header.html

Currently the [about section](https://not-matthias.github.io/apollo/about/) displays About as title but the [posts section](https://not-matthias.github.io/apollo/posts) and [projects section](https://not-matthias.github.io/apollo/projects/) just displays the site title, even though they both provide a title field:
https://github.com/not-matthias/apollo/blob/4b9787dd5b8ff70167e48f425bc7563196bc3002/content/about.md?plain=1#L2
https://github.com/not-matthias/apollo/blob/4b9787dd5b8ff70167e48f425bc7563196bc3002/content/posts/_index.md?plain=1#L4
This pr changed the behavior to use the section title if provided by the user, otherwise fallback to the site title is available.
For users prefer displaying the site title in section page, ~simply remove the title field in `_index.md` to keep the …

feat: display section title if provided

---

templates/homepage.html
templates/macros/macros.html

fixes #59 
Now, I decided to use the template method, as people may want to use this template more than once. So I provided a new macro and template. 
Here is an example:
```
+++
title= "Welcome to Apollo's Homepage!"
template = "homepage.html"
+++
Modern and minimalistic blog theme powered by [Zola](https://getzola.org). See a live preview [here](https://not-matthias.github.io/apollo).
<sub><sup>Named after the greek god of knowledge, wisdom and intellect</sup></sub>
1. Download the theme
```
git submodule add https://github.com/not-matthias/apollo themes/apollo
```
2. Add `theme = "apollo"` to your `config.toml`
3. Copy the example content
```
cp -r themes/apollo/content content
```
To enable MathJax equation rendering, set the variable `mathjax` to `true` in
the `extra` section of your …
```

added a homepage!

---

templates/macros/macros.html

I love apollo theme for Zola and I have started to use it for my blog. I found a link to a title is sometimes HTML escaped. According the Zola documentation, page's permalink doesn't need to be HTML escaped. This PR tries to fix it.
> We use the | safe filter because the permalink doesn't need to be HTML escaped (escaping would cause `/` to render as `&#x2F;`).
https://www.getzola.org/documentation/getting-started/overview/#blog-template

Disable HTML escaping for page's permalink

---

content/posts/configuration.md
sass/parts/_header.scss
sass/parts/_tags.scss
templates/partials/nav.html

This adds support for optionally displaying a logo image in the navigation bar. If the log image file is set via config.extra.logo in config.toml only then the logo is shown. The second commit adds documentation.

feat: logo support

---

content/posts/mermaid.md
templates/partials/header.html

Use `get_url` builder to ensure sites making use of the theme can still use mermaid.
Added some additional docs

fix: url builder for mermaid script src & added docs

---

templates/base.html

Two subsequent `<html>` tags were merged into a single one.

Remove superfluous second `<html>` tag

---

templates/macros/macros.html

Thank you for this fantastic theme!
This PR adds the option to show the word count on an article page.

Support word count on article

---

content/posts/math-symbol.md

I was looking at this example post about math notations, and I was setting up my own blog. It took me some time to figure out the `mathjax` configurations need to be in `[extra]` section.
So I am adding that information directly in the example post.

clarify mathjax configuration in [extra]

---

sass/parts/_tags.scss
templates/macros/macros.html
templates/page.html
templates/partials/header.html
templates/taxonomy_list.html

This PR adds support for displaying multiple authors in the post metadata.
- Introduced a new `authors` field in the front matter (`[author1, author2, ...]`)
- Updated the post template to render authors in a tags-like format
- Example output:
```
Posted on 2025-06-21 :: Updated on 2025-06-21 :: @author1 @author2 :: #tag1 #tag2
```
This addresses the discussion in #114 and follows the layout proposed in the comment thread. The goal is to provide a cleaner, more modern display of authors and tags in the metadata section.
- If `authors` is not present, the author section is omitted entirely, preserving the original layout format.
- Styling is kept consistent with the current theme.
Closes #114.

feat: add support for multiple authors in post metadata (closes #114)

---

content/_index.md

Fixes https://github.com/not-matthias/apollo/issues/131
Wherever I could, I've used [Zola internal linking](https://www.getzola.org/documentation/content/linking/), which fixes the markdown internal linking issue. These hyperlinks now render with the base URL taken into account.  
The above however only works for documents that exist before the build. Since taxonomies (e.g. `tags`) are generated dynamically, the `Taxonomies` link wasn't as easy to patch up. I've hardcoded it for now, but I'm not very happy about that approach. Looking for alternatives and I'm open to suggestions!
Regarding the taxonomy URL, the same issue has been [raised here](https://zola.discourse.group/t/link-to-taxonomies/512). `get_taxonomy` could be used to link to the `tags` index, but that'd need to be placed in …

fix: frontpage, feature section URLs

---

content/posts/configuration.md
content/projects/bacteria_in_porous_media.md
sass/parts/_cards.scss
templates/cards.html

Hello there!
While using the Apollo theme to build my personal page, I found myself wanting the ability to showcase projects with videos directly on the cards, similar to how images are handled. This PR aims to integrate that functionality.
This pull request introduces the ability to display videos in project cards, alongside existing image support.
- Adds `local_video` and `remote_video` extra variables to project front matter, allowing users to specify video paths.
- Implements `<video>` tag rendering in `cards.html` to display the videos.
- Introduces a `card-media` wrapper and associated CSS in `_cards.scss` to ensure consistent sizing and `object-fit: cover` for both images and videos, preventing layout distortion.
- Includes a new `bacteria_in_porous_media.md` project file and …

Feat: Add video support to project cards

---

sass/main.scss

This pull request makes a minor update to the `sass/main.scss` file by adding an import statement for `fonts.scss`, which ensures that custom fonts are included in the main stylesheet.
I don't know how this was working on your demo, but on my website everything broke when I updated the theme! And this fixed the issue.

Import fonts.scss in main.scss

---

config.toml
templates/partials/header.html

When using Mastodon, and probably other social networks on the Fediverse that implement the feature, it is possible for users to add author attribution on their website, so that when a link to the latter is published on the platform, the user profile is also inserted under the link preview.
With this PR, a user only needs to toggle the setting `fediverse` to `true`, and add its handle next to `fediverse_creator` in the config file to make it work.

Add fediverse author attribution

---

templates/cards.html
templates/macros/macros.html
templates/section.html
templates/talks.html

Allow displaying `_index.md` content on `section`, `cards` and `talks` template-based pages.
Example with cards content: https://mtsz.pl/oddam/

feat: show section content for section, cards, talks

---

README.md
content/posts/configuration.md
content/projects/_index.md
sass/parts/_cards.scss
templates/cards.html

Cards layout has fixed number of columns calculated based on card's min width, and fixed card height.
This PR implements dynamic min width calculation based on provided `cards_columns` count, and customizable card height via `card_media_height`.
Example with 3 columns: https://mtsz.pl/oddam/

feat: set number of columns and card height for cards template
